####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

import base64
import pickle
from typing import Any, Optional
from packet import Packet
from router import Router


type Addr = Any
type Port = Any
type Cost = int

# Heuristic
INFINITY = 200


class ForwardingTableEntry:
    def __init__(self, cost: Cost, next_hop: Optional[Addr] = None, port: Optional[Port] = None):
        self.cost = cost
        self.next_hop = next_hop
        self.port = port

class NeighborEntry:
    def __init__(self, cost: Cost, port: Port):
        self.cost = cost
        self.port = port

class DistanceVectorEntry:
    def __init__(self, cost: Cost, next_hop: Addr):
        self.cost = cost
        self.next_hop = next_hop


def serialize(obj: Any) -> str:
    bytes_ = pickle.dumps(obj)
    return base64.b64encode(bytes_).decode()

def deserialize(s: str) -> Any:
    obj = base64.b64decode(s.encode())
    return pickle.loads(obj)


# Who even names a class like this?
# Variables should have no underscore prefix
# (assuming this class is not used by any external authorities)
class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0

        # TODO
        #   add your own class fields and initialization code here
        self.__forwarding_table: dict[Addr, ForwardingTableEntry] = {}
        self.__forwarding_table[self.addr] = ForwardingTableEntry(cost=0, next_hop=self.addr, port=None)

        self.__neighbor_addrs_by_ports: dict[Port, Addr] = {}
        self.__neighbors_by_addrs: dict[Addr, NeighborEntry] = {}

    def handle_packet(self, port: Port, packet: Packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            if packet.dst_addr in self.__forwarding_table:
            #   send packet based on forwarding table, e.g., self.send(port, packet)
                entry = self.__forwarding_table[packet.dst_addr]
                if entry.cost < INFINITY and entry.port is not None:
                    self.send(entry.port, packet)
        else:
            distance_vector: dict[Addr, DistanceVectorEntry] = deserialize(packet.content)
            is_received_distance_vector_different = False

            for addr, entry in distance_vector.items():
                neighbor_addr = packet.src_addr
            # Hint: this is a routing packet generated by your routing protocol           
            # If the received distance vector is different
                if entry.cost == INFINITY:
                    if addr in self.__forwarding_table and self.__forwarding_table[addr].next_hop == neighbor_addr:
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
                        self.__forwarding_table[addr] = ForwardingTableEntry(cost=INFINITY, next_hop=None, port=None)
                        is_received_distance_vector_different = True

                else:
                    neighbor_cost = self.__neighbors_by_addrs[neighbor_addr].cost
                    new_neighbor_cost = min(entry.cost + neighbor_cost, INFINITY) # Bellman-Ford algorithm

                    if addr not in self.__forwarding_table or new_neighbor_cost < self.__forwarding_table[addr].cost:
                        neighbor_port = self.__neighbors_by_addrs[neighbor_addr].port
                        self.__forwarding_table[addr] = ForwardingTableEntry(cost=new_neighbor_cost, next_hop=neighbor_addr, port=neighbor_port)
                        is_received_distance_vector_different = True

            #   broadcast the distance vector of this router to neighbors
            if is_received_distance_vector_different:
                self.__broadcast_to_neighbors()

    def handle_new_link(self, port: Port, endpoint: Addr, cost: Cost):
        """Handle new link."""
        self.__neighbor_addrs_by_ports[port] = endpoint
        self.__neighbors_by_addrs[endpoint] = NeighborEntry(cost=cost, port=port)

        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        maybe_entry = self.__forwarding_table.get(endpoint)
        if maybe_entry is None or maybe_entry.cost != cost:
            self.__forwarding_table[endpoint] = ForwardingTableEntry(cost=cost, next_hop=endpoint, port=port)
        #   broadcast the distance vector of this router to neighbors
            self.__broadcast_to_neighbors()

    def handle_remove_link(self, port: Port):
        """Handle removed link."""
        neighbor_addr = self.__neighbor_addrs_by_ports.pop(port)
        del self.__neighbors_by_addrs[neighbor_addr]
        
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        for addr, entry in self.__forwarding_table.items():
            if entry.port == port:
                self.__forwarding_table[addr] = ForwardingTableEntry(cost=INFINITY, next_hop=None, port=None)

        #   broadcast the distance vector of this router to neighbors
        self.__broadcast_to_neighbors()

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors
            self.__broadcast_to_neighbors()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter(addr={self.addr})"

    def __broadcast_to_neighbors(self):
        for neighbor_addr, entry in self.__neighbors_by_addrs.items():
            distance_vector = {addr: DistanceVectorEntry(cost=INFINITY if neighbor_addr != addr and neighbor_addr == entry.next_hop else entry.cost, next_hop=entry.next_hop) for addr, entry in self.__forwarding_table.items()} # Poisoned reverse
            content = serialize(distance_vector)

            port = entry.port
            packet = Packet(kind=Packet.ROUTING, src_addr=self.addr, dst_addr=neighbor_addr, content=content)
            self.send(port, packet)
